networks:
  home_plants:
    driver: bridge

services:
  backend:
    container_name: django_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - home_plants
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://${DJANGO_POSTGRES_USER}:${DJANGO_POSTGRES_PASSWORD}@db:5432/home-plants
    depends_on:
      - db
      - pgadmin

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DJANGO_POSTGRES_NAME}
    networks:
      - home_plants
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - home_plants
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  pg_admin: