# Generated by Django 4.2.1 on 2024-06-25 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_product'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flowers', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='images_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.imagesfeedback', verbose_name='Фото пользователей'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Отзыв'),
        ),
    ]
