# Generated by Django 4.2.1 on 2024-06-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesfeedback',
            options={'verbose_name': 'Фото пользователя', 'verbose_name_plural': 'Фото пользователей'},
        ),
    ]
