# Generated by Django 4.2.1 on 2024-06-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='images_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.imagesfeedback', verbose_name='Фото пользователей'),
        ),
    ]
