# Generated by Django 4.2.1 on 2024-07-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.CharField(max_length=50, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название распродажи')),
                ('percent', models.IntegerField(verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Распродажа',
                'verbose_name_plural': 'Распродажи',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_image', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на картинку')),
                ('link_new', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на блог')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок блога')),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=50, null=True, verbose_name='Продукт')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowers_images', verbose_name='Изображение')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Скидка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.category', verbose_name='Категория')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.discount', verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
    ]
