# Generated by Django 4.2.1 on 2024-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Блог'},
        ),
    ]
