# Generated by Django 4.2.1 on 2024-07-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.discount', verbose_name='Размер скидки'),
        ),
    ]
