# Generated by Django 4.2.1 on 2024-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_flowers_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers_images', verbose_name='Изображение'),
        ),
    ]
