# Generated by Django 4.2.1 on 2024-07-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('status', models.CharField(choices=[('В корзине', 'В корзине'), ('Оформлен', 'Оформлен')], default='В корзине', max_length=20, verbose_name='Статус корзины')),
                ('is_feedback', models.BooleanField(default=False, verbose_name='Отзыв')),
                ('flowers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.flowers', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
