# Generated by Django 4.2.1 on 2024-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_product'),
        ('cart', '0003_delete_cartview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='flowers',
        ),
        migrations.AddField(
            model_name='cart',
            name='flowers',
            field=models.ManyToManyField(to='flowers.flowers', verbose_name='Растение'),
        ),
    ]
