# Generated by Django 4.2.1 on 2024-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_product'),
        ('cart', '0004_remove_cart_flowers_cart_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='flowers',
            field=models.ManyToManyField(null=True, to='flowers.flowers', verbose_name='Растение'),
        ),
    ]
