# Generated by Django 4.2.1 on 2024-06-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0002_flowers_product'),
        ('cart', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='flowers',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='flowers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.flowers', verbose_name='Растение'),
        ),
    ]
