# Generated by Django 4.2.1 on 2024-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('in_cart', 'В корзине'), ('ordered', 'Заказано')], default='in_cart', max_length=20, verbose_name='Статус корзины'),
        ),
    ]
