# Generated by Django 4.2.1 on 2024-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('В корзине', 'В корзине'), ('Оформлен', 'Заказано')], default='В корзине', max_length=20, verbose_name='Статус корзины'),
        ),
    ]
