# Generated by Django 4.2.1 on 2024-06-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_customer_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
