# Generated by Django 4.2.1 on 2024-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_flowers_alter_cart_user_cart_flowers'),
        ('order', '0008_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='cart.cart', verbose_name='Заказ'),
        ),
    ]
