# Generated by Django 4.2.1 on 2024-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_cart_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='summa',
            field=models.PositiveIntegerField(null=True, verbose_name='Сумма заказа'),
        ),
    ]
