# Generated by Django 4.2.1 on 2024-06-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_quantity_order_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('Заказ в обработке', 'Заказ в обработке'), ('Заказ готов', 'Заказ готов'), ('Заказ выполнен', 'Заказ выполнен')], default='Новый заказ', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taking',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Доставка', max_length=100, verbose_name='Тип получения'),
        ),
    ]
