# Generated by Django 4.2.1 on 2024-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status_alter_order_taking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('В обработке', 'В обработке'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен')], default='Создан', max_length=100, verbose_name='Статус'),
        ),
    ]
