# Generated by Django 4.2.1 on 2024-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('В обработке', 'В обработке'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='Создан', max_length=100, verbose_name='Статус'),
        ),
    ]
