# Generated by Django 4.2.1 on 2024-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taking',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=100, verbose_name='Тип получения'),
        ),
    ]
