# Generated by Django 4.2.1 on 2024-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_status'),
        ('order', '0016_alter_order_taking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taking_summa',
            field=models.CharField(choices=[(0, 0), (500, 500)], default=0, max_length=4, verbose_name='Сумма доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='cart.cart', verbose_name='Корзина для заказа'),
        ),
    ]
