# Generated by Django 4.2.1 on 2024-06-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_taking_alter_order_taking_summa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
