# Generated by Django 4.2.1 on 2024-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_purchasecart'),
        ('order', '0021_remove_order_status_order_is_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='cart.purchasecart', verbose_name='Корзина для заказа'),
        ),
    ]
